<?php

namespace Tests\Feature;

use App\Models\Category;
use Tests\TestCase;

class CategoryModelTest extends TestCase
{

    private $category;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->category = factory(Category::class)->create();
    }
    /**
     * @test
     * @testdox Adding Category
     */
    public function testNewCategory()
    {
        $this->assertDatabaseHas('categories', $this->category->getAttributes());

    }

    /**
     * @test
     * @testdox Updating Category
     */
    public function testUpdateCategory()
    {

        $this->category->is_active = false;
        $this->category->description = null;

        $this->category->save();

        $this->assertFalse($this->category->is_active);
        $this->assertNull($this->category->description);
        $this->assertDatabaseHas('categories', $this->category->getAttributes());
    }

    /**
     * @test
     * @testdox Showing Category
     */
    public function testShowCategory()
    {
        $this->assertDatabaseHas('categories', $this->category->getAttributes());
    }

    /**
     * @test
     * @testdox Removing Category
     */
    public function testDestroyCategory()
    {

        $this->category->delete();
        $this->assertSoftDeleted('categories', $this->category->getAttributes());
    }
}
