<?php

namespace Tests\Feature;

use App\Models\Gender;
use Tests\TestCase;

class GenderModelTest extends TestCase
{

    private $gender;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->gender = factory(Gender::class)->create();
    }

    /**
     * @test
     * @testdox Adding Gender
     * @group ignore
     */
    public function testNewGender()
    {
        $this->assertDatabaseHas('genders', $this->gender->getAttributes());

    }


    /**
     * @test
     * @testdox Updating Gender
     * @group ignore
     */
    public function testUpdateGender()
    {


        $this->gender->is_active = false;
        $this->gender->description = null;

        $this->gender->save();

        $this->assertFalse($this->gender->is_active);
        $this->assertNull($this->gender->description);

        $this->assertDatabaseHas('genders', $this->gender->getAttributes());
    }

    /**
     * @test
     * @testdox Showing Gender
     * @group ignore
     */
    public function testShowGender()
    {
        $this->assertDatabaseHas('genders', $this->gender->getAttributes());
    }

    /**
     * @test
     * @testdox Removing Gender
     * @group ignore
     */
    public function testDestroyGender()
    {

        $this->gender->delete();
        $this->assertSoftDeleted('genders', $this->gender->getAttributes());
    }
}
